### ISSUE TITLE
Section 3.1 query parameters

### ISSUE THREAD

**Issue by bohdanszymanik** [theimowski/SuaveMusicStoreTutorial#3]
In the code line
 pathScan "/store/details/%s/%d" (fun a id -> OK (sprintf "Artist: %s; Id: %d" a id))

a and id should be a tuple shouldn't they...

**Comment by theimowski** [comment]
yes you're right, would you like to send a PR?

**Comment by bohdanszymanik** [comment]
Sure - I've just given it a go - never done a pull request before so
hopefully, I've done it correctly.

Cheers,
Bohdan

On Tue, Jun 16, 2015 at 10:21 PM, Tomasz Heimowski <notifications@github.com

> wrote:
> 
> yes you're right, would you like to send a PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theimowski/SuaveMusicStoreTutorial/issues/3#issuecomment-112375357
> .

## 

---

Bohdan Szymanik
+64 21 530 079
http://bohdanszymanik.blogspot.com/

**Comment by theimowski** [comment]
yeah, everything's perfectly fine, thanks ;)
