### ISSUE TITLE
README.md: "Contents of this book are found __here__" - Just links to README.md again

### ISSUE THREAD

**Issue by jeroldhaas** [theimowski/SuaveMusicStoreTutorial#5]
Sentence in title of README.md doesn't point to a TOC, which would be very helpful in traversing this tutorial. Clicking on the link self-references to the README.md file again.

It would be nice to have a TOC.md file that linked to all the files, sorted / arranged in a particular order so as to make the beginning Suave.io user learn in a feature-progressive way: Concepts, configure, etc., in a linear fashion.

**Comment by jeroldhaas** [comment]
This issue either needs closed, or SUMMARY.md needs to be renamed to TOC.md. :smile:

**Comment by theimowski** [comment]
does this happen on GitBook or GitHub?

**Comment by jeroldhaas** [comment]
At Github, the link points to the project directory (https://github.com/theimowski/SuaveMusicStoreTutorial).

In the Gitbook, the link points to the project directory (https://github.com/theimowski/SuaveMusicStoreTutorial).

As I commented before, this issue may be a _moot point_: the link does, after all, say it's linking to the _contents_ of the book. However, it would be nice to provide a Table of Contents for those browsing the GitHub repository. [Summary.md](https://github.com/theimowski/SuaveMusicStoreTutorial/blob/master/SUMMARY.md) provides this, however doesn't seem to lead the user to click on it, due to its name (hence my suggestion to rename it to TOC.md :wink:).

**Comment by theimowski** [comment]
I think this is just the standard convention that GitBook has for section naming and as soon as it works and looks good on GitBook I wouldn't change it ;) closing

**Comment by jeroldhaas** [comment]
By no means am I trying to force the matter, however, I thought it might be helpful to mention that on GitBook, the structure / filenames can be changed in the GitBook config:

```
{
    "structure": {
        "summary": "TOC.md"
    }
}
```

...But, again, this is your prerogative. ;)

**Comment by theimowski** [comment]
Ok, changed the permalink to point to the Summary.md file instead of root of repository - does this help?

**Comment by jeroldhaas** [comment]
Yes, it does. :+1:  This will be easier for those trying to navigate the book. Thanks!
